

```{r, results = "hide", message = FALSE, message=FALSE}
phe_num <- x
out <- list()
for (cross_num in 1:5){
  #read test indicator file
  test_indicator <- readr::read_table(file = paste0("~/research/ukb-intervals/test_indicator_files/test_indicator_pheno_", phe_num, "_cross_", cross_num, "_ntest1000.txt"), col_names = FALSE)
  
  # read fam file
  fam <- readr::read_table(file = "~/research/predictionProject/plink_file/ukb/chr1.fam", col_names = FALSE) %>% 
    dplyr::mutate(test_indic = test_indicator$X1)
  ## define col_num
  col_num <- phe_num * 5 + (cross_num %% 5) + 1 
  ## 
  fam2 <- fam %>%
    dplyr::select(1, 2, dplyr::all_of(col_num), 131) %>%
    dplyr::filter(test_indic == 1)
  # read the profile files outputted by plink score allele
  scores <- list()
  for (chr_num in 1:22){
    #fn <- paste0("~/research/ukb-intervals/results/pheno", phe_num, "/predicted_ukb_cross", cross_num, "_chr", i, "_auto.dbslmm.txt.profile")
    fn <- paste0("~/research/ukb-intervals/results/pheno", phe_num, "/yangdbslmm/predicted_ukb_cross", cross_num, "_chr", chr_num, "_auto.dbslmm.txt.profile")
    scores[[chr_num]] <- readr::read_table(fn, col_names = TRUE)
    colnames(scores[[chr_num]]) <- paste0(colnames(scores[[chr_num]]), "_chr", chr_num)
  }
  scores2 <- lapply(X = scores, FUN = function(x){
    x %>% dplyr::select(6) # choose the SCORESUM column
  })
  scores_df <- do.call("cbind", scores2) %>% tibble::as_tibble() %>%
    dplyr::mutate(sum_scores = rowSums(.))
  s2 <- scores_df[1:1000,] %>%
    dplyr::select(sum_scores)
  fam3 <- fam2 %>%
    dplyr::mutate(predicted_value = s2$sum_scores) 
  out[[cross_num]] <- fam3 %>%
    dplyr::rename(true_pheno = 3)
}  
out_tib <- do.call("rbind", out) %>% 
  tibble::as_tibble() %>% 
  dplyr::select(- test_indic) %>%
  dplyr::mutate(residual = abs(true_pheno - predicted_value))
```

Now, we read in the plink score outputs and sum to get predicted values for the 
1000 subjects belonging to the validation set.

```{r, results='hide', message = FALSE}
# read true pheno file for validation set
fn <- paste0("~/research/comparisonProject/03_subsample/continuous/pheno", phe_num, "/val/ukb/02_pheno_c.txt")
validation_true_pheno_tib <- readr::read_table(fn, col_names = FALSE)
# get the five versions of predicted values for the validation set subjects
out <- list()
for (cross_num in 1:5){
  foo <- list()
  for (chr_num in 1:22){
    fn <- paste0("~/research/ukb-intervals/results/pheno", 
               phe_num, 
               "/validation-set_predicted_ukb_cross", 
               cross_num, 
               "_chr", 
               chr_num, 
               "_auto.dbslmm.txt.profile")
    foo[[chr_num]] <- readr::read_table(fn)
  }
  out[[cross_num]] <- foo 
}
# sum for each cross num
pred_vals_validation_set <- list()
for (cross_num in 1:5){
  # rename cols in each list's elements (tibbles)
  s2 <- list()
  for (chr_num in 1:22){
    s2[[chr_num]] <- out[[cross_num]][[chr_num]] %>%
      dplyr::select(6)  # choose only the SCORESUM column
      colnames(s2[[chr_num]]) <- paste0(colnames(s2[[chr_num]]), "_chr", chr_num) 
  }
  scores_df <- do.call("cbind", s2) %>% 
    tibble::as_tibble() %>%
    dplyr::mutate(sum_scores = rowSums(.)) %>%
    dplyr::select(sum_scores) %>%
    dplyr::rename(predicted_value = sum_scores)
  colnames(scores_df) <- paste0(colnames(scores_df), "_cross", cross_num)
  pred_vals_validation_set[[cross_num]] <- scores_df
}
pred_vals_validation_set_tib <- do.call("cbind", pred_vals_validation_set) %>%
  tibble::as_tibble() %>%
  dplyr::mutate(true_pheno = validation_true_pheno_tib$X1)
```



```{r}
get_fitted <- function(index, fitted_vec){
  fitted_vec[index]
}
intervals <- list()
for (i in 1:1000){
  ### take one validation set observation
  out2 <- out_tib %>%
    dplyr::mutate(cross_membership = rep(1:5, each = 1000))
   o3 <- out2 %>% 
     dplyr::mutate(fitted_cv =  purrr::map_dbl(.x = cross_membership, .f = get_fitted, fitted_vec = as.vector(unlist(pred_vals_validation_set_tib[i, 1:5])))) %>% # calculate mu hat (X_{n + 1})
     dplyr::mutate(fitted_minus_residual = fitted_cv - residual, fitted_plus_residual = fitted_cv + residual)
  ## determine quantiles - type 6?  of fitted_minus_residual and fitted_plus_residual
  intervals[[i]]<- c(quantile(o3$fitted_minus_residual, prob = alpha / 2, type = 6), 
  quantile(o3$fitted_plus_residual, prob = 1 - alpha / 2, type = 6))
}
```


## Coverage for Trait `r x`

```{r}
do.call("rbind", intervals) %>% 
  tibble::as_tibble() %>%
  dplyr::rename(left = 1, right = 2) %>%
  dplyr::mutate(true_pheno = pred_vals_validation_set_tib$true_pheno) %>%
  dplyr::mutate(in_interval = true_pheno <= right & true_pheno >= left) %>%
  dplyr::summarise(coverage = mean(in_interval))
```

