---
title: "Overlapping problem"
author: "Frederick J. Boehm"
date: "`r Sys.Date()`"
output: html_document
---

It looks like my current versions of the validation-ids.txt and verification-ids.txt files have subjects that are in the training and test sets, for example, for fold 5.
We need to fix this so that, collectively, the validation and verification sets have only the subjects that are not in the test and training sets.

First, let's read a fam file with all 337,000+ subjects.

```{r}
library(magrittr)
```

```{r}
fam_file <- "../dat/plink_files/ukb/chr22.fam"
fam_tib <- vroom::vroom(fam_file, col_names = FALSE)
verif_ids <- vroom::vroom(file = "dat/simulations-ding/verification-ids.txt", col_names = FALSE)
valid_ids <- vroom::vroom(file = "dat/simulations-ding/validation-ids.txt", col_names = FALSE)
training_ids5 <- vroom::vroom(file = "dat/simulations-ding/training-ids-fold5.txt", col_names = FALSE)
test_ids5 <- vroom::vroom(file = "dat/simulations-ding/test-ids-fold5.txt", col_names = FALSE)
sum(duplicated(c(test_ids5$X1, training_ids5$X1, verif_ids$X1, valid_ids$X1)))

```

```{r}
# remake the validation and verification sets
# first, define the union of the valid and verif sets
ver_and_val <- setdiff(fam_tib$X1, union(training_ids5$X1, test_ids5$X1)) 
set.seed(2022-06-27)
ver <- sample(x = ver_and_val, size = 1000, replace = FALSE)
val <- setdiff(ver_and_val, ver)
```

```{r}
tibble::tibble(X1 = ver, X2 = ver) %>%
  dplyr::arrange(X1) %>%
  vroom::vroom_write(file = "../dat/simulations-ding/verification-ids.txt")
```

```{r}
tibble::tibble(X1 = val, X2 = val) %>%
  dplyr::arrange(X1) %>%
  vroom::vroom_write(file = "../dat/simulations-ding/validation-ids.txt")
```

```{r}
sum(duplicated(c(val, ver, training_ids5$X1, test_ids5$X1)))
length(c(val, ver, training_ids5$X1, test_ids5$X1))
```


