---
title: "Cross-validation-plus for UKB traits"
author: "Frederick J. Boehm"
date: "`r Sys.Date()`"
output: 
  bookdown::html_document2:
    number_sections: false
params:
  trait_type: "binary"
  trait_number: 50
  nfold: 50
---

```{r}
(trait_type <- params$trait_type)
(trait_number <- params$trait_number)
(nfold <- params$nfold)

library(magrittr)
```


## Custom R code

It should be straightforward to use DBSLMM outputs and fam files to write custom code for CV+.





```{r, echo = TRUE, message = FALSE}
alpha <- 0.1
fbstr <- paste0("~/research/ukb-intervals/study_nfolds/", nfold, "-fold/")
out <- list()
if (trait_type == "continuous") {
    output_dir <- paste0(fbstr, "05_internal_c/pheno", trait_number, "/cvplus/")
} else {
    output_dir <- paste0(fbstr, "06_internal_b/pheno", trait_number, "/cvplus/")
}
res_file <- paste0(output_dir, "res.rds")

if (!file.exists(res_file)) {
  	res <- lapply(trait_number, function(x) {
		knitr::knit_child(
		'~/research/ukb-intervals/study_nfolds/code/02_method/cv-plus-child.Rmd', 
		envir = environment(), 
		quiet = TRUE
		)
    get("out")
	})
  	saveRDS(res, file = res_file)
} else {
  	res <- readRDS(res_file)
}
```

```{r, eval = TRUE}
coverages <- lapply(X = res, 
                    FUN = function(mytib){
  mytib %>%
	dplyr::summarise(coverage = mean(in_interval, na.rm = TRUE))
       }
)
cov1k <- lapply(X = res, 
                    FUN = function(mytib){
  mytib %>%
    dplyr::summarise(coverage = mean(in_interval[1:1000], na.rm = TRUE))
       }
) 
cov10k <- lapply(X = res, 
                    FUN = function(mytib){
  mytib %>%
    dplyr::summarise(coverage = mean(in_interval[1:10000], na.rm = TRUE))
       }
) 

coverage_tib <- do.call("rbind", coverages) %>%
  tibble::as_tibble() %>%
  dplyr::mutate(trait_num = seq_along(res))
coverage_tib %>%
  gt::gt()

```

```{r, eval = TRUE}
cov_tib <- tibble::tibble(verif_size = c(length(res[[1]]$in_interval), 10000, 1000), 
                         coverage = c(unlist(coverages), unlist(cov10k), unlist(cov1k)))
cov_tib %>%
  gt::gt()
```





