

```{r, results = "hide", message = FALSE}
phe_num <- x
# read true pheno values file
fam_file <- paste0(fbstr, "plink_file/ukb-hapmap3/", trait_type, "/chr22.fam")
fam <- vroom::vroom(fam_file, col_names = FALSE)
``` 

```{r}
# make a true pheno column vector
true_pheno_vec <- apply(MARGIN = 1, 
	X = fam[, (5 + nfold * (phe_num - 1) + 1):(5 + nfold * phe_num)], 
	FUN = function(x){
		foo <- x[!is.na(x)]
		if (length(foo) > 0){
			out <- max(foo)
		} else {
			out <- NA
		}
		return(out)
})

true_pheno_tib <- fam %>%
					dplyr::select(1,2) %>%
					dplyr::mutate(true_pheno = true_pheno_vec) %>%
					dplyr::rename(FID = X1, IID = X2)

```




```{r}
out <- list()
for (cross_num in 1:nfold){
	## define col_num
#	col_num <- 2 + cross_num
#	fam2 <- fam_all %>%
#		dplyr::select(1, 2, dplyr::all_of(col_num), 8) 
	# read the profile files outputted by plink score allele
	scores <- list()
	for (chr_num in 1:22){
		if (trait_type == "continuous"){
			fn <- paste0(fbstr, "05_internal_c/pheno", 
					phe_num, 
					"/DBSLMM/pred_ukb_best_cross", 
					cross_num, 
					"_chr", 
					chr_num, 
					".profile")
		} else {
			fn <- paste0(fbstr, "06_internal_b/pheno", 
					phe_num, 
					"/DBSLMM/pred_ukb_best_cross", 
					cross_num, 
					"_chr", 
					chr_num, 
					".profile")
					}
		scores[[chr_num]] <- readr::read_table(fn, col_names = TRUE)
		colnames(scores[[chr_num]]) <- paste0(colnames(scores[[chr_num]]), "_chr", chr_num)
	}
	scores2 <- lapply(X = scores, FUN = function(x){
		x %>% dplyr::select(6) # choose the SCORESUM column
	})
	scores_df <- do.call("cbind", scores2) %>%
					tibble::as_tibble() %>%
					dplyr::mutate(sum_scores = rowSums(.))
	s2 <- scores_df %>%
		dplyr::select(sum_scores) %>%
		dplyr::bind_cols(scores[[1]][, 1:2]) %>% # add the identifiers, FID and IID
		dplyr::rename(FID = FID_chr1, IID = IID_chr1) # fix identifier names
	# read idx file
	if (trait_type == "continuous") {
		idx_fn <- paste0(fbstr, "02_pheno/01_test_idx_c/idx_pheno", phe_num, "_cross", cross_num, ".txt")
	} else {
		idx_fn <- paste0(fbstr, "02_pheno/04_test_idx_b/idx_pheno", phe_num, "_cross", cross_num, ".txt")
	}
	idx <- readr::read_table(idx_fn, col_names = FALSE) %>%
		dplyr::rename(fam_id = 1, subject_id = 2) %>%
		dplyr::select(fam_id)
	#fam3 <- fam2 %>%
	#	dplyr::rename(fam_id = 1) %>%
	#	dplyr::right_join(idx, by = "fam_id") %>%
	#	dplyr::left_join(s2, by = c("fam_id" = "FID"))
	
	
	out[[cross_num]] <- s2 %>%
		dplyr::mutate(cross_membership = cross_num) 
}
out_tib <- do.call("rbind", out) %>% 
  tibble::as_tibble() %>% 
  dplyr::left_join(true_pheno_tib) %>%
  #dplyr::mutate(true_pheno = true_pheno_vec) %>%
  dplyr::mutate(residual = abs(true_pheno - sum_scores))
```

Now, we read in the plink score outputs and sum to get predicted values for the subjects belonging to the verification set.

```{r, results='hide', message = FALSE}
# read verif ids file for verification set
if (trait_type == "continuous"){
  fn <- paste0(fbstr, "03_subsample/continuous/pheno", phe_num, "/verif/03_idx_pheno.txt")
} else {
  fn <- paste0(fbstr, "03_subsample/binary/pheno", phe_num, "/verif/03_idx_pheno.txt")
}
verif_true_pheno <- readr::read_table(fn, col_names = FALSE) %>%
                              dplyr::arrange(X1) %>%
                              dplyr::rename(FID = X2, IID = X1, true_pheno = X3)
# get the nfold versions of predicted values for the verification set subjects
out2 <- list()
for (cross_num in 1:nfold){
  foo <- list()
  for (chr_num in 1:22){
    if (trait_type == "continuous"){
      fn <- paste0(fbstr, "05_internal_c/pheno", 
               phe_num, 
               "/DBSLMM/verif_pred_ukb_best_cross", 
               cross_num, 
               "_chr", 
               chr_num, 
               ".profile")
    } else {
      fn <- paste0(fbstr, "06_internal_b/pheno", 
               phe_num, 
               "/DBSLMM/verif_pred_ukb_best_cross", 
               cross_num, 
               "_chr", 
               chr_num, 
               ".profile")
    }
    foo[[chr_num]] <- readr::read_table(fn)
  }
  out2[[cross_num]] <- foo 
}
# sum for each cross num
pred_verification_set <- list()
for (cross_num in 1:nfold){
  # rename cols in each list's elements (tibbles)
  ss <- list()
  for (chr_num in 1:22){
    if (chr_num == 1){
      ss[[chr_num]] <- out2[[cross_num]][[chr_num]] %>%
        dplyr::select(1, 6)  # choose only the SCORESUM column, unless it's chr1
        colnames(ss[[chr_num]])[2] <- paste0(colnames(ss[[chr_num]])[2], "_chr", chr_num) 
    } else {
      ss[[chr_num]] <- out2[[cross_num]][[chr_num]] %>%
        dplyr::select(6)  # choose only the SCORESUM column
        colnames(ss[[chr_num]]) <- paste0(colnames(ss[[chr_num]]), "_chr", chr_num) 
    }
  }
  scores_df <- do.call("cbind", ss) %>% 
    tibble::as_tibble() %>%
    dplyr::mutate(sum_scores = rowSums(.[, -1])) %>%
    dplyr::select(1, sum_scores) %>%
    dplyr::rename(predicted_value = sum_scores)
  colnames(scores_df) <- paste0(colnames(scores_df), "_cross", cross_num)
  pred_verification_set[[cross_num]] <- scores_df
}
pred_verification_set_tib <- do.call("cbind", pred_verification_set) %>%
  tibble::as_tibble() %>%
  dplyr::rename(FID = FID_cross1) %>%
  dplyr::left_join(true_pheno_tib)
```



```{r, message = FALSE}
get_fitted <- function(index, fitted_vec){
  fitted_vec[index]
}
n_verif <- nrow(verif_true_pheno)
#n_verif <- 1000
intervals <- list()
for (i in 1:n_verif){
	if (i %% 1000 == 0) print(i)
	### take one verification set observation
	o3 <- out_tib %>% 
				dplyr::mutate(fitted_cv =  purrr::map_dbl(.x = cross_membership, 
														.f = get_fitted, 
														fitted_vec = as.vector(unlist(pred_verification_set_tib[i, 2 * (1:nfold)])))
					) %>% # calculate mu hat (X_{n + 1})
		dplyr::mutate(fitted_minus_residual = fitted_cv - residual,
					fitted_plus_residual = fitted_cv + residual)
	## determine quantiles of fitted_minus_residual and fitted_plus_residual
	intervals[[i]] <- tibble::tibble(FID = pred_verification_set_tib$FID[i],
									left = quantile(o3$fitted_minus_residual,
												probs = alpha,
												na.rm = TRUE),
									right = quantile(o3$fitted_plus_residual,
														probs = 1 - alpha,
														na.rm = TRUE)
									)
}
```


## Coverage for Trait `r x`

```{r}
mytib <- intervals %>% 
  			dplyr::bind_rows() #%>%
mytib_outfile <- paste0(fbstr, trait_type, "-intervals-pheno", phe_num, ".rds")
saveRDS(object = mytib, file = mytib_outfile)
```

```{r, eval = TRUE}

# need a join with the idx_pheno object containing true phenotype values
mytib2 <- mytib %>%
	dplyr::left_join(verif_true_pheno, by = "FID") %>%
	dplyr::mutate(in_interval = true_pheno <= right & true_pheno >= left) %>%
	dplyr::mutate(interval_width = right - left)
 

```

```{r}
assign(x = "out", value = mytib2)
```





