---
title: "Summarise MCCP outputs"
author: "Frederick J. Boehm"
date: "`r Sys.Date()`"
output: 
  bookdown::html_document2:
    number_sections: false
---


```{r}
library(magrittr)
```

```{r}
library(ggplot2)
alpha <- 0.05
phe_nums <- 1:25
mean_predictability <- list()
combined <- list()
for (phe_num in phe_nums){
	mccp_file <- paste0("/net/mulan/disk2/fredboe/research/ukb-intervals/study_nfolds/5-fold/mccp/pred", phe_num, ".out")
	dat <- vroom::vroom(mccp_file)
	input_file <- paste0("/net/mulan/disk2/fredboe/research/ukb-intervals/study_nfolds/5-fold/mccp/test", phe_num, ".txt")
	input <- vroom::vroom(input_file)
	combined[[phe_num]] <- dat %>%
					dplyr::bind_cols(input) %>%
					dplyr::mutate(concordance = predictStatus == true_pheno) %>%
					dplyr::mutate(expit_PRS = locfit::expit(PRS)) %>%
					dplyr::mutate(trait_num = phe_num)
	mean_predictability[[phe_num]] <- combined[[phe_num]] %>% 
		dplyr::mutate(predictable = (prob_control < alpha & prob_case >= alpha) | (prob_case < alpha & prob_control >= alpha)) %>%
		dplyr::summarise(mean_pred = mean(predictable))
}
```

```{r}
trait_names <- c("PRCA", "TA", "TD2", "CAD", "RA", 
                     "BRCA", "AS", "MP", "MDD", "SS", 
                     "QU", "HT", "FFI", "DFI", "OS", 
                     "AN", "GO", "SAF", "HA", "TE", 
                     "T1B", "VMS", "MY", "SN", "ES")
full_names <- c("Prostate Cancer",
				"Tanning Ability",
				"Type 2 Diabetes Mellitus",
				"Coronary Artery Disease",
				"Rheumatoid Arthritis",
				"Breast Cancer",
				"Asthma",
				"Morning Person",
				"Major Depressive Disorder",
				"Smoking status",
				"Qualification",
				"Hypertension",
				"Fresh Fruit Intake",
				"Dried Fruit Intake",
				"Osteoarthritis",
				"Angina",
				"Gout",
				"Salt Added To Food",
				"Headache",
				"Tense",
				"Type I Balding",
				"Supplementary Vitamin and Mineral",
				"Myxedema",
				"Snoring",
				"Ever Smoked"
				)

mean_predictability %>% 
	unlist() %>% 
	tibble::as_tibble() %>%
	dplyr::rename(mean_predictability = value) %>%
	dplyr::mutate(trait_num = 1:25) %>%
	dplyr::mutate(trait_name = trait_names, full_name = full_names) %>%
	dplyr::arrange(desc(mean_predictability))
```

## Plots for logistic transformation

```{r}
for (trait in 1:25){
	fig_fn <- here::here("Rmd", paste0("expitPRS_vs_prob_control_trait", trait, ".png"))	
	c2 <- combined[[trait]] %>% 
		dplyr::select(predictStatus, prob_control, prob_case, PRS, expit_PRS, sex) 
	c2 %>%	
		ggplot(aes(x = prob_control, y = expit_PRS, colour = as.factor(sex))) + geom_point() + ggtitle(full_names[trait])
	ggsave(fig_fn)
}
```

```{r}
fig_fn <- here::here("Rmd", "expitPRS_vs_probcontrol-all-traits.png")
combined %>%
	dplyr::bind_rows() %>%
	ggplot(aes(x = prob_control, y = expit_PRS, colour = as.factor(sex))) + geom_point() +  facet_wrap(vars(trait_num))
ggsave(fig_fn)
```
